### PR TITLE
add git to end of apt command for install, CentoOS chamged tp CentOS

### PR DESCRIPTION
**Pull request by MParvin**
I got some error `git: command not found`, So I added git to be install with apt command.

### CODE REVIEW

**Comment by MParvin** [comment]
In Debian 10, liberasurecode-dev must be installed.

**Comment by MParvin** [comment]
When installing gluster-swift in Debian 10, this error appears:
`Can not locate liberasurecode.so.1`
To resolve this issue we must run this commnad before install:
```apt install liberasurecode-dev```

**Comment by amarts** [comment]
@MParvin I should warn, this repository is not maintained since almost 18+ months.

What is the usecase you are trying to solve?

**Comment by MParvin** [comment]
@amarts I want to use Gluster as Object storage, so I found this repository.
What did I do wrong?

**Pull request closed without merging**
